### ISSUE TITLE
maxDepth exceeded when dragging items with children

### ISSUE THREAD

**Issue by csabip** [primetwig/react-nestable#1]
react-nestable is perfect for my needs except... If you set your nestable's maxDepth to 2 and you drag an item with a child, you can create a tree with 3 levels. Is there a way to prevent this? or an option to allow/disallow it?

**Comment by primetwig** [comment]
thanks for your feedback.
I'll add a check which will prevent nesting in this case.

**Comment by primetwig** [comment]
fixed in 1.0.12

**Comment by csabip** [comment]
Awesome, you spared me many many hours wirh your module for which i am grateful! Thank you!

**Comment by primetwig** [comment]
Cool! You can add a star if you find it useful 😃
