### ISSUE TITLE
Changing the icon

### ISSUE THREAD

**Issue by magdalko** [primetwig/react-nestable#12]
Hi, 
Would be nice to change the icon of collapse :)

Best wishes

**Comment by primetwig** [comment]
you can add some styles, like:
```
.nestable-item-icon.icon-minus-gray {
    background: linear-gradient(to bottom, transparent 30%, pink, green, transparent 70%);
}
```
need another way?

**Comment by primetwig** [comment]
`1.1.0`: added `renderCollapseIcon` which accepts a render function.
