### ISSUE TITLE
onChange function implementation issue

### ISSUE THREAD

**Issue by amitmaars** [primetwig/react-nestable#13]
onChange - Callback which has two parameters: items - new array after position was changed, item - item which has been moved.

I have tried. But something went wrong, I'm not getting the data.
 
If you could provide some example.

**Comment by primetwig** [comment]
try to run this:
```
<Nestable
    items={[{ id: 1 }, { id: 2 }, { id: 3 }]}
    renderItem={el => 'ID: '+el.id}
    onChange={(items, item) => console.log({ items, item })}
/>
```

**Comment by amitmaars** [comment]
Thanks.
