### ISSUE TITLE
CSS not loading?

### ISSUE THREAD

**Issue by bknill** [primetwig/react-nestable#16]
CSS and icons not loading with example? 

![image](https://user-images.githubusercontent.com/7074483/41814589-2c530f50-77a6-11e8-9ce2-deef3b5c1cf9.png)

`  
import Nestable from 'react-nestable'
render(){

    const items = [
      { id: 0, text: 'Andy' },
      {
        id: 1, text: 'Harry',
        children: [{ id: 2, text: 'David' }],
      },
      { id: 3, text: 'Lisa' },
    ]

    const renderItem = ({ item }) => {
      return item.text
    }

    return(<Nestable
      items={items}
      renderItem={renderItem}
    />)
  }`

**Comment by primetwig** [comment]
Hello, this may be an issue of your settings.
Try to setup a blank project (e.g. with create-react-app) and add all your setting to it one by one.
