### ISSUE TITLE
2 items, dragging one above the other they have same name

### ISSUE THREAD

**Issue by bknill** [primetwig/react-nestable#17]
I have 2 items

![image](https://user-images.githubusercontent.com/7074483/41824496-32d88534-7865-11e8-9324-a7b1535fd68f.png)

I drag the bottom one to the top

![image](https://user-images.githubusercontent.com/7074483/41824501-511cb5ec-7865-11e8-8b81-9191e4347b6f.png)

They both have the same text

This is how I'm using your excellent component

    ` render(){

    const {items} = this.state

    const renderItem = ({ item,collapseIcon }) => {

      return <SectionItem
        item={item}
        selectItem={this.onSelectItem.bind(this)}
        updateTitle={this.onUpdateTitle.bind(this)}
        collapseIcon={collapseIcon} />
    }

     return(<div className={'sections'}>
      <Nestable
        items={items}
        renderItem={renderItem}
        onChange={this.onChange.bind(this)}
      />

      <div onClick={() =>this.addSection()} className={'add-section'}>
        <i className={'fa fa-plus'}/> <span>MODULE</span>
      </div>
    </div>)
    }
    }
  
        class SectionItem extends Component{

    constructor(props) {
    super(props)
     this.state ={
      isExpanded:false,
      item: props.item,
      title: props.item.text || ''}
    }
  
    onChangeTitle(event){

    const title = event.target.value
      this.setState({title})
     }

     render () {

    const {collapseIcon, item, selectItem} = this.props
    const {isExpanded,title} = this.state

    return (<div className={'section'}>
      <div onClick={()=> selectItem(item)} className={'section-header'}>
        <div className={'draggable'}/>
        {collapseIcon}
        <span>{title}</span>
        <div onClick={()=> this.setState({isExpanded: !isExpanded})} className={'action'}>
          <i className={`fa fa-angle-${isExpanded ? 'up' : 'down'}`}/>
        </div>
      </div>
      {
        isExpanded &&
          <div className={'edit'}>
            <input value={title} onChange={this.onChangeTitle.bind(this)}/> <i className={'fa fa-times'}/>
          </div>
      }
    </div>)
     }
    }`

**Comment by primetwig** [comment]
it looks like u mutate your items.
could you setup some codepen/jsfiddle example?
