### ISSUE TITLE
request: drop event 

### ISSUE THREAD

**Issue by bknill** [primetwig/react-nestable#19]
I'm planning on using this component to allow the item to be dropped 'elsewhere'

Could you expose the drop event to get the coordinates?

**Comment by primetwig** [comment]
you should use different lib for that, like `react-dnd`.
PS: i may remove drag events in future for supporting touch.

**Comment by bknill** [comment]
Thanks I tried merging them, but didn't really work. 

Your simple nesting method is too good to use anything else!
