### ISSUE TITLE
You are manually calling a React.PropTypes validation function

### ISSUE THREAD

**Issue by andrewGuscha** [primetwig/react-nestable#2]
1. Warning: You are manually calling a React.PropTypes validation function for the `items` prop on `Nestable`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

2. You are manually calling a React.PropTypes validation function for the `threshold` prop on `Nestable`.
3. You are manually calling a React.PropTypes validation function for the `maxDepth` prop on `Nestable`.
4. You are manually calling a React.PropTypes validation function for the `childrenProp` prop on `Nestable`.
5. You are manually calling a React.PropTypes validation function for the `renderItem` prop on `Nestable`.
6. You are manually calling a React.PropTypes validation function for the `onChange` prop on `Nestable`.

**Comment by primetwig** [comment]
Can not reproduce with react@15.4.2.
Could you make a small fiddle? You can use my examples from example dir.

**Comment by andrewGuscha** [comment]
I get this warnings on react@15.1.0
Everything is fine on react@15.4.2
