### ISSUE TITLE
Collapse Icon not showing

### ISSUE THREAD

**Issue by robwheatley** [primetwig/react-nestable#27]
I'm having a play with this in a prototype app I'm putting together. Loving it so far especially vs the other drag and drop nested lists code I've played with. 

It's all going very well so far, but for the life of me, I can't get the collapse icons to show.

When I do an inspect on the page, they are sort of there and the collapse functionality works, its just that the icon itself isn't showing. I'm coding locally using Meteor, but I have the same issue in my codesandbox I used as the initial play area.

Here's the sandbox. It's got some crap in it from when I was playing with jquery illegally removing stuff from the DOM to mess with React, so don't worry about the project title or nonsense in there. The bulk of the code is a straight copy from one of your examples.

https://codesandbox.io/s/illegal-react-removal-8i044?fontsize=14

Any thoughts?

**Comment by primetwig** [comment]
Hi.
Icon is supposed to get loaded by css as a background image.
I'm not sure about a correct way to do that in your sandbox.
Nevertheless, you can override icon classnames to set your own icons.

**Comment by robwheatley** [comment]
Thanks for the response.

Figured as much - I'll have a play doing that. 

Because I'm using React Material-UI for this prototype, I'm also tempted to drop one of their icons in there instead.
