### ISSUE TITLE
How to connect two Nestables?

### ISSUE THREAD

**Issue by DarkAnfi** [primetwig/react-nestable#28]
I have this code:
`
class Content extends React.Component {

  render() {
    const items1 = [
      { id: 0, text: 'Andy' },
      {
        id: 1, text: 'Harry',
        children: [{ id: 2, text: 'David' }]
      },
      { id: 3, text: 'Lisa' }
    ];

    const items2 = [
      { id: 4, text: 'Andy' },
      {
        id: 5, text: 'Harry',
        children: [{ id: 6, text: 'David' }]
      },
      { id: 7, text: 'Lisa' }
    ];

    const renderItem = ({ item }) => {
      return item.text;
    };

    return (
      <Container fluid className="Content">
        <Row>
          <Col xs="6">
            <Nestable items={items1} renderItem={renderItem} />
          </Col>
          <Col xs="6">
            <Nestable items={items2} renderItem={renderItem} />
          </Col>
        </Row>
      </Container>
    );
  }
}
`

And I need to connect both Nestables, in such a way that I can share elements of one in the other.

Can anybody help me?

**Comment by primetwig** [comment]
Hi. This is not possible. Sorry.

**Comment by SapneshNaik** [comment]
@primetwig any workaround for this? I want to add elements to the nestable tree from another tree
