### ISSUE TITLE
Read-only option

### ISSUE THREAD

**Issue by RobrechtM** [primetwig/react-nestable#30]
First of all, love the component!

Is it possible to add a `disabled` prop, which makes the whole list read-only? Thanks!

**Comment by primetwig** [comment]
Hi, it is not obvious, but you can pass a `handler` and not use it in render.
I'm considering pros/cons and name of other approaches.

**Comment by RobrechtM** [comment]
For now it does the trick. Thanks!

**Comment by SapneshNaik** [comment]
Implement the `confirmChange` method for the tree and just return false to disable any movement.
