### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by AxelPariss** [primetwig/react-nestable#31]
Hi ! I try to use your package but when i import it with : 
`import Nestable from 'react-nestable';`

I have this error :
![image](https://user-images.githubusercontent.com/17270429/63301600-3edfee00-c2db-11e9-961a-d9677f660d55.png)

I tried to update Yarn, NPM, all of my packages but I still don't understand why I have this error. Do You have an idea ?

PS: I use electron with this boilerplate : [https://github.com/electron-react-boilerplate/electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

**Comment by primetwig** [comment]
hi.
it looks like you have an issue with `css-loader` or whatever you use.
it suffers while trying to import styles.
your call stack tells me that in the file `dist/Nestable/Nestable.js` on the line 33 is a `require('./Nestable.css')`.
it uses your `internal/modules/cjs/helpers.js` and gets an error on line 20 of that file.
