### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by tanftw** [primetwig/react-nestable#34]
Hi George, do you have any planning for TypeScript support?

**Comment by primetwig** [comment]
I'd like to have it, but I do not maintain it a lot at the moment. Any help is welcome.

**Comment by p8ul** [comment]
In your root folder add this folders `@types/react-nestable` then add a `index.d.ts`. Copy the code below in the file.

```ts
declare module 'react-nestable' {
  import * as React from 'react';

  export type Item = {
    id: string;
    text: string;
    children?: Item[];
    nestedIn?: string | null;
    link?: string | null;
    type?: number;
  };
  export default class Nestable extends React.Component<{
    items: Item[];
    handler?: React.ReactNode;
    renderItem: (arg: {
      item: Item;
      collapseIcon: React.ReactNode;
      index: number;
      handler: React.ReactNode;
    }) => React.ReactNode;
    maxDepth: number;
    renderCollapseIcon?: (args: { isCollapsed: boolean }) => React.ReactNode;
    onChange: (items: Item[]) => void;
    confirmChange: (dragItem: Item, destinationParent: Item) => boolean;
  }> {}
}

```

**Comment by herudi** [comment]
> In your root folder add this folders `@types/react-nestable` then add a `index.d.ts`. Copy the code below in the file.
> 
> ```ts
> declare module 'react-nestable' {
>   import * as React from 'react';
> 
>   export type Item = {
>     id: string;
>     text: string;
>     children?: Item[];
>     nestedIn?: string | null;
>     link?: string | null;
>     type?: number;
>   };
>   export default class Nestable extends React.Component<{
>     items: Item[];
>     handler?: React.ReactNode;
>     renderItem: (arg: {
>       item: Item;
>       collapseIcon: React.ReactNode;
>       index: number;
>       handler: React.ReactNode;
>     }) => React.ReactNode;
>     maxDepth: number;
>     renderCollapseIcon?: (args: { isCollapsed: boolean }) => React.ReactNode;
>     onChange: (items: Item[]) => void;
>     confirmChange: (dragItem: Item, destinationParent: Item) => boolean;
>   }> {}
> }
> ```

Cool . . Great thanks...

**Comment by herudi** [comment]
Now, to support typescript i'm install from here
`yarn add https://github.com/primetwig/react-nestable/archive/8455e656aa8d7e379042517bf50505d446a78f88.tar.gz`

**Comment by jezswift** [comment]
Hi @primetwig , any chance you could quickly include the type defs created by @herudi in the dist folder.
This would be a great and hopefully a quick fix.

Many thanks in advance,

**Comment by primetwig** [comment]
done in 2.0.0
