### ISSUE TITLE
Changes are not saved if setState is present in the onChange function

### ISSUE THREAD

**Issue by jlei523** [primetwig/react-nestable#35]
```javascript
        <Nextable
          items={this.state.items}
          ref={el => (this.refNestable = el)}
          onChange={this.onDragChange}
        />
```

```javascript
  onDragChange(items, item) {
    this.setState({
      anystate: anychange
    })
  }
```

Whenever this.setState is in the onChange function, drag and drop does nothing. The items do not move. 

Any ideas?

**Comment by primetwig** [comment]
Nestable is a [controlled component](https://www.robinwieruch.de/react-controlled-components). Do you update `items` in your state?

**Comment by jlei523** [comment]
Thanks for the reply.

I don't update items in my state. In fact, I don't even have `items` in my state at all. It's an object outside of the React class.

Note that running this.setState for any state, even states that have nothing to do with Nestable, will cause Nestable to not apply drag changes.

```javascript
onDragChange(items, item) {
    this.setState({
      anyState: "any change"
    });
  }
```

```javascript
      <Nestable
        collapsed
        items={items}
        renderItem={renderItem}
        handler={<span style={handlerStyles} />}
        ref={ref}
        onChange={(items, item) => onChange(items, item)}
      />
```

**Comment by primetwig** [comment]
You have `<Nestable items={items}`. How exactly do you store `items`?
If you create it during every render, than updating the local state would create a new instance of items, which would be equal the initial shape of items.
Example: `<Nestable items={items.slice(0)}` will restore the initial `items` on every render of a parent component.

**Comment by jlei523** [comment]
> You have `<Nestable items={items}`. How exactly do you store `items`?
> If you create it during every render, than updating the local state would create a new instance of items, which would be equal the initial shape of items.
> Example: `<Nestable items={items.slice(0)}` will restore the initial `items` on every render of a parent component.

Right now I'm just storing it in an object outside of the class. I have a function to convert that object into an object that works with Nestable.

```javascript
let costCentersTest = {
  "1": "HEAD OFFICE",
  "2": "UK",
  "3": "INTERNATIONAL",
  "2-4": "UK > MANCHESTER",
  "2-5": "UK > LONDON",
  "2-5-7": "UK > LONDON > VAN-1",
  "2-5-7-9": "UK > LONDON > VAN-1 > DRIVER-1",
  "2-5-8": "UK > LONDON > VAN-2",
  "2-5-8-10": "UK > LONDON > VAN-2 > DRIVER-2",
  "2-6": "UK > BIRMINGHAM"
};

class CostCenters extends Component {
  constructor(props) {
    super(props);
    this.state = {
      needsSave: false,
      newCostCenterName: "",
      userChangedItems: []
    };

    this.onDragChange = this.onDragChange.bind(this);
  }

  async componentDidMount() {
    const response = await fetch(baseUrl + "/api/cost_centres_get");
    const data = await response.json();
    console.log(data);
    this.setState({
      items: convertCostCentersIntoItems(data)
    });
  }

  collapse = collapseCase => {
    if (this.refNestable) {
      switch (collapseCase) {
        case 0:
          this.refNestable.collapse("NONE");
          break;
        case 1:
          this.refNestable.collapse("ALL");
          break;
        case 2:
          this.refNestable.collapse([1]);
          break;
      }
    }
  };

  onDragChange(items, item) {}

  updateInputValue = event => {
    this.setState({
      newCostCenterName: event.target.value.toUpperCase()
    });
  };

  submitNewCostCenter = () => {
    let obj = {
      id: 10,
      text: this.state.newCostCenterName
    };

    this.setState({
      items: this.state.items.concat(obj)
    });
  };

  render() {
    return (
      <div>
        <Controls
          updateInputValue={this.updateInputValue}
          submit={this.submitNewCostCenter}
          cancel={this.hideNewCostCenterInput}
          collapse={this.collapse}
        />

        <Nextable
          items={convertCostCentersIntoItems(costCentersTest)}
          ref={el => (this.refNestable = el)}
          onChange={this.onDragChange}
        />
      </div>
    );
  }
}
```

**Comment by primetwig** [comment]
`convertCostCentersIntoItems(costCentersTest)` creates you a new instance of the Array every time component gets rerendered, which resets the internal state of Nestable.

**Comment by jlei523** [comment]
> `convertCostCentersIntoItems(costCentersTest)` creates you a new instance of the Array every time component gets rerendered, which resets the internal state of Nestable.

What's a way to fix this? Thanks!

**Comment by primetwig** [comment]
Try to use [memo pattern](https://codeburst.io/understanding-memoization-in-3-minutes-2e58daf33a19).
`convertCostCentersIntoItems` should as an example make a "shallow equal" check and return a new instance only when date was actually changed.

**Comment by jlei523** [comment]
> Try to use [memo pattern](https://codeburst.io/understanding-memoization-in-3-minutes-2e58daf33a19).
> `convertCostCentersIntoItems` should (as an example) make a "shallow equal" check and return a new instance only when data was actually changed.

If I use one of the example objects that don't need any formatting, it's still the same issue. IE. If I clone the example, add a this.setState to the onChange function, it'll still have the same issue.

Is there a pattern that you recommend without having to resort to using memo?

**Comment by primetwig** [comment]
Check this part: https://github.com/primetwig/react-nestable/blob/master/src/Nestable/Nestable.js#L85
You have at least these 2 to be always new on every render:
```
handler={<span style={handlerStyles} />}
onChange={(items, item) => onChange(items, item)}
```
`handler` can be saved into top level variable.
`onChange` can be passed as is.

**Comment by jlei523** [comment]
> Check this part: https://github.com/primetwig/react-nestable/blob/master/src/Nestable/Nestable.js#L85
> You have at least these 2 to be always new on every render:
> 
> ```
> handler={<span style={handlerStyles} />}
> onChange={(items, item) => onChange(items, item)}
> ```
> 
> `handler` can be saved into top level variable.
> `onChange` can be passed as is.

Ahh! The issue seemed to be handler. If I remove handler, it worked without changing anything with items.

```javascript
      <Nestable
        collapsed
        items={items}
        renderItem={renderItem}
        ref={ref}
        onChange={onChange}
      />
```

> `handler` can be saved into top level variable.
Can you show me what you mean by this?

This caused the same rerender issue.
```javascript
  const Handler = () => {
    return <span style={handlerStyles} />;
  };

      <Nestable
        collapsed
        items={items}
        renderItem={renderItem}
        handler={<Handler />}
        ref={ref}
        onChange={onChange}
      />
```

**Comment by primetwig** [comment]
```
const handler = <span style={handlerStyles} />;
<Nestable handler={handler} />
```

**Comment by jlei523** [comment]
> ```
> const handler = <span style={handlerStyles} />;
> <Nestable handler={handler} />
> ```

Worked! Thank you for your help!
