### ISSUE TITLE
Prevent adding top offset in Firefox on scrolled page

### ISSUE THREAD

**Issue by andrewGuscha** [primetwig/react-nestable#4]
Here some screenshots from Firefox
1. Page not scrolled: http://dl3.joxi.net/drive/2017/06/02/0000/1791/22271/71/61108e804a.png
2. Page scrolled: http://dl3.joxi.net/drive/2017/06/02/0000/1791/22271/71/60e2dc3240.png

Moved item shifts down on the scroll top value in Firefox.
All is well in Chrome.

**Comment by primetwig** [comment]
I'm not used to FF.
PR is welcome.

**Comment by ahmadsholehin** [comment]
Not sure if this is related, but there is a big offset for nestable-item-copy (relative to how much the page is scrolled) in Chrome as well.

Looks like a CSS issue.

<img width="1192" alt="screen shot 2018-02-07 at 7 00 56 pm" src="https://user-images.githubusercontent.com/2733543/35913337-3e48603e-0c3a-11e8-81c9-8476a30d2dcd.png">

**Comment by iamfeek** [comment]
Hi, I am the team member of @ahmadsholehin. The fix was a lifesaver for us here and we just wanna have a shoutout to you for it!

**Keep it up!**
