### ISSUE TITLE
Encountering Syntex error when trying to import Nestable into application

### ISSUE THREAD

**Issue by jabberw0ky** [primetwig/react-nestable#41]
![Nestable Error2](https://user-images.githubusercontent.com/40864140/73175313-bb62ce00-40be-11ea-8b66-aaf9ccfc15d7.png)

I am trying to import the package into my app but it keeps giving me this error. Any help would be appreciated.

**Comment by primetwig** [comment]
Hi!
How do you compile your app? webpack/CRA/etc.
Do you have svg files in your app? check if you can put one, import it and render.

**Comment by jabberw0ky** [comment]
> Hi!
> How do you compile your app? webpack/CRA/etc.
> Do you have svg files in your app? check if you can put one, import it and render.

![Untitled](https://user-images.githubusercontent.com/40864140/73245957-52349680-4162-11ea-82a9-71505bd235e1.png)

I am using webpack and this is the webpack config for svg loader...and no i dont think i have svg files atm..

**Comment by primetwig** [comment]
try to use file loader instead. and put one file into your project to make sure you have set it up correctly. you will remove it afterwards.

**Comment by jabberw0ky** [comment]
Yeah the file loader worked.. i had to remove all of the other loaders for the SVG as well to get it running... Thanks a bunch mate
