### ISSUE TITLE
How to revert the state of items inside a custom onChange?

### ISSUE THREAD

**Issue by christoph-kluge** [primetwig/react-nestable#43]
Thank you for creating this library! In less than 2 hours I was able to migrate away from an existing jquery-nestable component to this neat react-nestable view  👍

Now I'm facing some issues that I am not able to revert the state inside my `onChange()` handler when the handler (API call) is failing. I did check the source and tried to use `dragRevert()` but the state is already gone at this point in time. I  have a ugly workaround for it by using `ref` and passing it a little back and forth to reset the previous state but it feels wrong to me.

While having this in mind I was asking myself why `onChange` does not support the bool return value the same way as `confirmChange`? 

Does it make sense to add an "auto-revert on onChange fail" feature for this? I'm fine to contribute here.

**Comment by primetwig** [comment]
Hi there.
In every `onChange` you have access to prev and next states of the value.
So you can use it as controlled component and update your local state to keep whatever value you need.

**Comment by christoph-kluge** [comment]
Thanks for the quick response! Can you lead me to the line where this is happening?

The only thing I saw was this line here. 

```
onChange && isDirty && onChange(items, dragItem);
```

In a nutshell this is my current situation:

```
<Nestable 
    onChange={(items, item) => this.onChangeHandler(this, items, item)}
    ref={el => this.refNestable = el}
/>
```

```
onChangeHandler(page, items, item) { 
    axios.put((response) => {...})
        .then((response) => { 
             // display success message
        })
        .catch((err) => {
           // revert Nestable to the previous state
          page.refNestable.setState({
            items: page.getNestableItems(),
            itemsOld: null,
            dragItem: null,
            isDirty: false,
          });
        });
}
```

**Comment by primetwig** [comment]
you are not supposed to use `ref` besides methods that are described as public.
you need something like this:
```
class YourComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: [],
      lastSavedItems: null,
    };
  }
  onChange = items => {
    this.setState({ items });
    axios
      .put(/* ... */)
      .then(() => this.setState({ lastSavedItems: items })) // and show success if needed
      .catch(() => this.setState({ items: this.state.lastSavedItems })) // and show error if needed
  }
  render() {
    return (
      <Nestable 
        onChange={this.onChange}
        items={this.state.items}
      />
    );
  }
}
```

**Comment by christoph-kluge** [comment]
Thank you @primetwig. This is a nice solution. 

Somehow I got stucked trying to handle the revert inside your component and totally forgot that I can handle it easily outside 👍
