### ISSUE TITLE
Prevent auto loading of css

### ISSUE THREAD

**Issue by smeijer** [primetwig/react-nestable#52]
Is there a way to not automatically include the `css` file? I would like to create my own styling, and the auto-import of the stylesheet makes this harder than strictly required.

**Comment by HikeNalb** [comment]
The autoloading also makes the module incompatible with Next.js. 
Next.js does not allow css imports from within the module. 
Getting this error:
![image](https://user-images.githubusercontent.com/74308495/101246407-d14c1100-371b-11eb-8bf5-318ce04c1c11.png)

**Comment by primetwig** [comment]
done in 2.0.0
