### ISSUE TITLE
rtl direction

### ISSUE THREAD

**Issue by badie21** [primetwig/react-nestable#58]
hey everyone.is there anyone to help me to add rtl direction to this package?

**Comment by primetwig** [comment]
Hi. Any problem with `renderItem`? Do you have any screenshots to share?

**Comment by SaeedKhodajoo** [comment]
i have the same problem
any idea?

**Comment by badie21** [comment]
https://github.com/badie21/react-nestable
I worked on this issue 2 years ago. I forked the project and solved this problem but I don't know why but I did not make any pull request that day.please check this forked project and tell me if I can give you more help

**Comment by badie21** [comment]
> i have the same problem any idea?

https://github.com/badie21/react-nestable
I worked on this issue 2 years ago. I forked the project and solved this problem but I don't know why but I did not make any pull request that day.please check this forked project and tell me if I can give you more help

**Comment by primetwig** [comment]
if you could set up some example for me to check what's going on with a different translation, I would try to help make it look good or fix any issues I encounter. thank you.
