### ISSUE TITLE
onChange get parentItem

### ISSUE THREAD

**Issue by rickvandermey** [primetwig/react-nestable#6]
Hi,

When I change a item's position, I would like to know where it has moved to.
To be more specific, in the onChange function I would like to see parentItem. 

Is this already possible and if so, do you have a small fiddle.

**Comment by primetwig** [comment]
Hello.

I wish I knew the way you follow to sort items.
Some people respect order of items in array,
but others use prop `position` in every item.

Nestable has a method `getPathById(id, items)`.
You can try to use it directly (so far I have no intention to change it),
or better copy it to your utils (just for being on a safe side).

Your code would look something like:
```
state = {
  items: [] // let's say your items are in state
};
handleChange = (items, item) => {
  const from = refToNestable.getPathById(item.id, this.state.items);
  const to = refToNestable.getPathById(item.id, items);
};
```
Please notice another method as well: `getItemByPath(path, items)`.

**Comment by rickvandermey** [comment]
I rewrote the layout for my json to your example to minimize bugs.
I've played a little with those functions but ended up in writing a function 

maybe it is helpfull for this project to implement to get the parent

`processArray(id, array, parentId) {
    array.map((i) => {
      const itemId = i.id;
      if(itemId != null && itemId === id) {
        if(parentId){
          this.props.actions.patchSortedPage(id, parentId);
        }
      }
      if(typeof(i.children) === 'object' && i.children.length > 0) {
        return this.processArray(id, i.children, itemId );
      }
    });
  }`
