### ISSUE TITLE
Is there a option for disable the dragging?

### ISSUE THREAD

**Issue by ozaimoglu** [primetwig/react-nestable#65]
Sometimes I need to disable dragging, is there a option for it?

**Comment by primetwig** [comment]
You can use drag `handler` and do not render it.

**Comment by breiko83** [comment]
Hey - is this the correct answer? 

I tried passing both false or nil to handler but the whole item becomes draggable.

**Comment by primetwig** [comment]
> Hey - is this the correct answer?
> 
> I tried passing both false or nil to handler but the whole item becomes draggable.

Try passing component and ignore it in rendering. Looks weird, but I consider better ways in future.
```
// use external variable to omit redundant re-rendering
const handlerStub = () => <span />

// handler prop will be draggable here
// but you can refrain from rendering it
const renderItem = ({ item, handler }) => item.text

const Example = () => (
  <Nestable
    items={items}
    renderItem={renderItem}
    handler={handlerStub}
  />
)
```

**Comment by breiko83** [comment]
Thanks @primetwig - it works.
