### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by zain-ak** [primetwig/react-nestable#67]
Hey, first of all... great library, very easy to use and customize for the most part!

I was wondering if I could add animations to the list, specifically, when you collapse or expand I'd like it to be smoother. 

I get the feeling this is probably a simple thing to do with className prop? But I'm not sure how to go about it.

Thanks!

**Comment by zain-ak** [comment]
Also, could I just completely disable dragging? I've done where it doesn't move anything, but could I remove all the animations for it too?

**Comment by primetwig** [comment]
Hi!
Animations are not supported yet.

> could I just completely disable dragging?

there is a kinda hacky way for now. check #65 for more info

**Comment by primetwig** [comment]
`disableDrag` prop is added now as well for convenience.
