### ISSUE TITLE
Allow hook for list of collapsed IDs

### ISSUE THREAD

**Issue by Chillout93** [primetwig/react-nestable#71]
Hey there, awesome library!

I'm looking to update a list of collapsed IDs each time a user clicks the collapse button, I was thinking of hooking into the renderCollapseIcon for the onClick but then I don't believe I have anyway of defining which IDs are collapsed or not?

This would be great so I could for example, save the IDs in local storage and have user saved state. 

Cheers,
Nick

**Comment by primetwig** [comment]
hi. thank you for the feature request. the `onCollapseChange` callback is added. cheers
