### ISSUE TITLE
Confirm after dropped Item and before rendering

### ISSUE THREAD

**Issue by tabunan** [primetwig/react-nestable#74]
Hello,

Nice package.

I`m currently working on a set of groups items. A parent can't drag and set as a child then a child can't drag or set as a parent. So far I can do this using confirmChange the only problem is that if the parent does not have a child you can't drop to item.
`
  confirmChange = ({dragItem, destinationParent}) => {

     if( dragItem.parent == 0 && destinationParent) { return false }

     if( dragItem.parent != 0 && !destinationParent ) { return false}

    return true;
  }
`
I hope it makes sense :)

**Comment by primetwig** [comment]
you could check if `destinationParent` has children and handle that case with another `if` statement.
would that do the trick?
if not, then some live example would help understand the issue (feel free to reopen).
