### ISSUE TITLE
How can I use onChange method?

### ISSUE THREAD

**Issue by MarcianoAntonacciPXL** [primetwig/react-nestable#76]
I'm attempting to use the onChange method to receive the new items array. I already tried a lot of methods but it doesn't seem to work. Any ideas how I should do it? Thanks

`Code:

              const { totalCount, results } = data;
              let nestableObjects = [];
              const reversedResults = results.reverse();

              reversedResults.forEach(res => {
                nestableObjects.push({
                  id: res.id,
                  name: res.name,
                  children: [],
                });
              });

              reversedResults.forEach(obj => {
                if (obj.object !== null) {
                  const parentObject = nestableObjects.find(
                    p => p.id === obj.object.id,
                  );
                  if (parentObject !== undefined) {
                    const childObject = nestableObjects.find(
                      c => c.id === obj.id,
                    );
                    parentObject.children.push(childObject);
                    nestableObjects = nestableObjects.filter(
                      o => o.id !== obj.id,
                    );
                  }
                }
              });

              nestableObjects = nestableObjects.reverse();

              return (
                <div>
                  <p>{JSON.stringify(nestableObjects)}</p>
                  <Nestable
                    items={nestableObjects}
                    renderItem={renderItem}
                    handler={<Handler />}
                    renderCollapseIcon={({ isCollapsed }) => (
                      <Collapser isCollapsed={isCollapsed} />
                    )}
                  />
                </div>
              );`

**Comment by primetwig** [comment]
@dinhnhobao thank you for the help.
few things to notice:
1. `items` is a prop of an object and not a direct value, so:
`onDragEnd = (items) => {` --> `onDragEnd = ({ items }) => {`
2. you don't need to do a deep copy, it may slow down the rendering if there are too many elements.
simply saving it to state and avoiding direct mutations on it should be enough.
