### ISSUE TITLE
Configuring which item can be picked up/dropped on

### ISSUE THREAD

**Issue by merwaaan** [primetwig/react-nestable#8]
Hi,
Is there currently a way to allow picking/dropping for individual items?

Use case: a file/folder hierarchy.
* Files can be picked (`allowPick: true`) but they cannot be dropped on (`allowDrop: false`).
* Folders can be picked and dropped on (`allowPick: true`, `allowDrop: true`).
* Some special folders could also not be pickable, such as root folders (`allowPick: false`, `allowDrop: true`).

If this is not currently possible and there is interest in this feature, I can propose a patch.

**Comment by primetwig** [comment]
Hello,

There is no such props yet.

I see it as a way to make some items disabled (you can not drag it).
These items will get some css class, so styling will be on your own.
But there are two ways of doing it:
1. item has to have a prop (e.g. `disabled`, but may be adjusted by some settings)
2. Nestable can have prop `disabledItems`, which is an array of ids

And I can forbid item to accept children (so you wont be able to drop inside that item).

If you want to implement it, please make it as separate features.
Thank you.

**Comment by primetwig** [comment]
You can now use `confirmChange` to validate if dropping is allowed.
See example 3: https://primetwig.github.io/react-nestable/dist/example/
