### ISSUE TITLE
include disable Drag

### ISSUE THREAD

**Issue by johny-lopes** [primetwig/react-nestable#85]
Could include the option to disable Drag of table lines

**Comment by dinhnhobao** [comment]
+1. Anyone knows if there is a workaround for this?

**Comment by primetwig** [comment]
Check #65 for now

**Comment by dinhnhobao** [comment]
@primetwig The solution works perfectly! That's great. Thank you so much!

**Comment by johny-lopes** [comment]
Thank you @primetwig the solution worked correctly.

**Comment by primetwig** [comment]
`disableDrag` prop is added and will be available in the upcoming release. stay tuned.
