### ISSUE TITLE
Hide collapsible icon when dragging

### ISSUE THREAD

**Issue by dinhnhobao** [primetwig/react-nestable#86]
Hi,
I want the `react-nestable` to be such that, when an item is being dragged, the collapsible icon can be hidden. Since the collapsible icon does not have a unique id for every item, is there anyway I can identify the collapsible icon belonging to the block being dragged and hide it? 

For example, here is the initial state without dragging
![image](https://user-images.githubusercontent.com/43085789/155343306-1e951e3f-1719-43ba-aa98-9f2e9e83e5f2.png)

Once I am dragging the block, I want the collapsible icons to disappear (circled below)
![image](https://user-images.githubusercontent.com/43085789/155343462-562a4a39-f536-4062-bd0d-c9d1c1a39b3c.png)

Thanks a lot!

**Comment by dinhnhobao** [comment]
Answer - I was wrong. The collapsible icon can be assigned an id via the `renderItem` method
![image](https://user-images.githubusercontent.com/43085789/155346328-5d60672e-554d-429c-982b-291a0d3ed3c8.png)

**Comment by primetwig** [comment]
@dinhnhobao I've added that event, so it will be available in the upcoming version. stay tuned.
