### ISSUE TITLE
Getting Error while dragging expanded list to the bottom

### ISSUE THREAD

**Issue by Priyanshu921** [primetwig/react-nestable#89]
getting this error when dragging expanded list to the bottom

![image](https://user-images.githubusercontent.com/54221295/163142401-eb93f871-1713-4e70-82a5-ab172466d5f0.png)

**Comment by primetwig** [comment]
@Priyanshu921 thank you for reporting.
I need you to help me understand the issue better.
Does it happen during the first move?
Or you make one move, in which you may mutate the list which you receive on the `onChange` callback, then you get this error in a subsequent move?

**Comment by primetwig** [comment]
Can not reproduce. Feel free to re-open with more details.
