### ISSUE TITLE
react-nestable not working in IE-11

### ISSUE THREAD

**Issue by kishore-dumpa** [primetwig/react-nestable#9]
Hi,

I would like to use react-nestable it's working in all the browsers but not on IE11. 
Is it possible to use react-nestable on IE11 ?

Regards,
Kishore

**Comment by primetwig** [comment]
Hello,
I don't have IE atm. Could you be more specific and give me a log from console or some other info about the issue?

**Comment by kishore-dumpa** [comment]
Hi @primetwig 

Thanks for quick reply, can you please and check with the below

![react_dnd](https://user-images.githubusercontent.com/6139661/30536012-e3b32dc0-9c81-11e7-9c4f-57d2560a4d4f.PNG)

**Comment by gnarmedia** [comment]
@kishore-dumpa It seems like you may need to transpile the es6 down to browser ready es5. `babel src -d dist`, this of course requires babel to be installed. Hope this helps, if not, let me know.

**Comment by primetwig** [comment]
I still have no chance to test it in IE (I am not a Windows user).
However I have made some changes, so please update to 1.0.19 and check if issue was fixed.
Thank you.

**Comment by primetwig** [comment]
will close for now

**Comment by jai1331** [comment]
react-nestable is fulfills my requirement except IE support,It would be helpful if this plugin supports IE also and deliberately I need this feature. Any update on this will be helpful.

**Comment by jai1331** [comment]
react-nestable fulfills my requirement except IE support,It would be helpful if this plug-in supports IE and deliberately I need this feature. Any update on this will be helpful.

**Comment by jai1331** [comment]
To make react-nestable work in IE, do add this in nestable.js file : 

`var isIE = /*@cc_on!@*/false || !!document.documentMode;
var box = (isIE) ? elem.getClientRects() : elem.getBoundingClientRect();
var top = box.top + scrollTop - clientTop;`

and for this line target.matches && target.matches(selector) , need Polyfill as this link suggests [https://developer.mozilla.org/en-US/docs/Web/API/Element/matches](url)

above changes did a trick for me @primetwig

**Comment by Prashant2903** [comment]
i want to perform CRUD operation in react-nestable
